# Generated by Django 5.1.3 on 2024-12-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modsmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perevod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('size', models.IntegerField(verbose_name='Размер')),
                ('photo', models.URLField(verbose_name='Иконка перевода')),
                ('genre', models.CharField(max_length=200, verbose_name='Жанр')),
                ('notforchildren', models.BooleanField(default=False, verbose_name='Запрещено для детей')),
                ('link', models.URLField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Перевод',
                'verbose_name_plural': 'Переводы',
            },
        ),
    ]
